### ISSUE TITLE
Spotify Playlist Side Menu

### ISSUE THREAD

**Issue by morgansliman** [spotitube-team/SpotiTube#11]
- [x] Migrate current sidebar to more versatile version
- [x] Display User Playlists - Name & length
- [x] Style Playlist Content
- [x] Pagination Button - show If user has >20 playlists
- [x] Append next page of playlists to bottom on button press

**Comment by tachprime** [comment]
Needs some more styling but for the most part this feature is done,  will add some CSS to handle some container sizing and fixed scrolling later.
